/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "AddrLow.h"
#include "AddrHigh.h"
#include "DataInput.h"
#include "CE.h"
#include "CE_aliases.h"
#include "OE.h"
#include "OE_aliases.h"
#include "Clock_1.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Pin_1.h"
#include "Pin_1_aliases.h"
#include "Pin_2.h"
#include "Pin_2_aliases.h"
#include "Pin_3.h"
#include "Pin_3_aliases.h"
#include "Pin_4.h"
#include "Pin_4_aliases.h"
#include "Pin_5.h"
#include "Pin_5_aliases.h"
#include "Pin_6.h"
#include "Pin_6_aliases.h"
#include "Pin_7.h"
#include "Pin_7_aliases.h"
#include "Pin_8.h"
#include "Pin_8_aliases.h"
#include "Pin_9.h"
#include "Pin_9_aliases.h"
#include "Pin_10.h"
#include "Pin_10_aliases.h"
#include "Pin_11.h"
#include "Pin_11_aliases.h"
#include "Pin_12.h"
#include "Pin_12_aliases.h"
#include "Pin_13.h"
#include "Pin_13_aliases.h"
#include "Pin_14.h"
#include "Pin_14_aliases.h"
#include "Pin_15.h"
#include "Pin_15_aliases.h"
#include "Pin_16.h"
#include "Pin_16_aliases.h"
#include "Pin_17.h"
#include "Pin_17_aliases.h"
#include "Pin_18.h"
#include "Pin_18_aliases.h"
#include "Pin_19.h"
#include "Pin_19_aliases.h"
#include "Pin_20.h"
#include "Pin_20_aliases.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "cy_em_eeprom.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

